Add more maps
QutEcoacoustics/workbench-client pull request #2038
Opened 2023-02-03 09:00 UTC by hudson-newey

# Add more maps

Users have expressed a lack of geographical information from the list and home pages. Therefore, to show more geographical information, I have added a map to the home page and list pages.

## Changes

- Adds a `baw-site-map` to the home page
- Adds a `baw-site-map` to the project and list pages that displays all sites in the filter (if the filter is updated, the sites update)
- Adds tests for maps on home, project & region list pages
- Fixes a bug where if a used clicked on a non-clickable map, it'd throw a JavaScript console error

## Problems

None

## Issues

Fixes: #2027 

## Visual Changes

**Project and list site pages:**
![image](https://user-images.githubusercontent.com/33742269/216556750-cbcced71-4cbe-460f-8bd5-f0316ec50d03.png)

**Home Page:**
![image](https://user-images.githubusercontent.com/33742269/216556858-5b0a9c2e-8ef2-4c5e-9b9e-c71bd623c246.png)

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

2023-02-27 07:49 UTC, atruskie requested changes
Ok my main feedback is in this comment: https://github.com/QutEcoacoustics/workbench-client/issues/2027#issuecomment-1445517077

I think we can vastly simplify the site-map component.  Change the query to a `GET /sites` which by default shows all sites. Then add `projects` and `regions` filter inputs (possibly even just ids) which filter the fetch all for the sites. This would satisfy every use case:

- show one site ` <baw-site-map [sites]=[sites] ></baw-site-map>`
- show sites in a region  `<baw-site-map [regions]=[regions] ></baw-site-map>`
- show sites in a project  `<baw-site-map [projects]=[projects] ></baw-site-map>`
- show all sites `<baw-site-map ></baw-site-map>`

2023-02-27 07:49 UTC, atruskie commented on src/app/components/home/home.component.html
> +<!-- Live an interactive map -->
What aspect of this is live?

2023-02-27 07:49 UTC, atruskie commented on src/app/components/home/home.component.spec.ts
> +      });
empty test?

2023-02-27 07:49 UTC, atruskie commented on src/app/components/home/home.component.ts
> +        : this.projectApi.filter(filter);
why don't we just query for all sites?

2023-02-27 07:49 UTC, atruskie commented on src/app/components/home/home.component.ts
> +  }
some notes:

- just select all sites
- you can disable paging on the request using the `disable_paging` option https://github.com/QutEcoacoustics/baw-server/wiki/API:-Spec#specialized-patterns
- you must not pull back full sized site objects. Use the projection API filters to only pull back the values you need (id, name, lat/long).
    - you'll need a custom service method

2023-02-27 07:49 UTC, atruskie commented on src/app/components/home/home.component.ts
> +  }
Also, I think we can strip all this logic and my suggestions out and move it into the component

2023-03-09 00:51 UTC, hudson-newey commented on src/app/components/home/home.component.html
> +<!-- Live an interactive map -->
I agree, no aspect of the map is live. I have changed this comment to better reflect this section

```html
<!-- All sites map -->
```

2025-09-25 01:16 UTC, closed without merging