Fix: project shown in titles when projects hidden
QutEcoacoustics/workbench-client pull request #2062
Opened 2023-05-25 07:21 UTC by hudson-newey

Fixes: #2052

# Bug Fix: project shown in titles when projects hidden

Since regions still technically have a parent project item, when projects were hidden, the project model name was still emitted in the route title.

This is incorrect as users should not see any project information if projects are hidden

## Changes

Added condition in route title builder to use a shallow region route instead of project route if projects are hidden

## Problems

Adds a _TODO_ stating that we may want to refactor the route title builder in the future to use the menu service's `rootToMenuRoute()` method. This method is not currently exposed as public, and causes circular dependencies in the current architecture.

## Issues

Fixes: #2052 

## Visual Changes

From:
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/09877dcd-f069-4a86-8f2e-0ea29bf15fdb)

To:
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/12e47352-d6b9-436a-843c-7cfbf2f5ea54)

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

2023-05-25 22:52 UTC, atruskie requested changes
Isn't there a better way to achieve this?

The title is used by the menuroute attached to the page... shouldn't all the project hidden routes/menus be in their own hierarchy which doesn't include project as a parent?

I checked and it doesn't look this is how we've setup our menu routes.

So:

- we could make sure these sub-pages use a menuroute hierarchy that is distinct (which naturally avoids the problem but could explode menu route comlexity)
- or we could put the decision into whether or not to show a title in the hands of the title maker. I.e. the project menu route title function should do something like ` hideProjects ? null : 'normal title'`. We'd probably inject an options hash into the title lambda then.

Either way the logic here should belong outside the app.component, perhaps except for injecting the required options.

2023-05-31 23:50 UTC, hudson-newey commented
> or we could put the decision into whether or not to show a title in the hands of the title maker. I.e. the project menu route title function should do something like ` hideProjects ? null : 'normal title'`. We'd probably inject an options hash into the title lambda then.

I've implemented this, however, I've realized that it generates route titles that are not consistent with the rest of the client.

E.g.

![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/8f347a5b-2499-400f-898f-76851431cd16)
_Project route title_

![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/24bbdcb9-5727-4db7-8054-e4992be08fe2)
_Site route title when projects are hidden_

I expect the result to be "<<brandName>> | Sites | aaa" not "<<brandName>> | aaa"

This arises because sites should actually be mounted under the `shallowRegion` route when projects are hidden (as is with the breadcumbs and secondary menu).

Therefore, we should probably go with the second proposed option

> we could make sure these sub-pages use a menuroute hierarchy that is distinct (which naturally avoids the problem but could explode menu route comlexity)

2023-06-02 00:50 UTC, atruskie approved these changes
Looks great!

2023-06-02 01:02 UTC, hudson-newey commented
Will be fixing test dependency error before merging

2023-06-02 05:02 UTC, hudson-newey commented
I've updated the tests to [test each route title](https://github.com/QutEcoacoustics/workbench-client/pull/2062/files#diff-a7029529e750e168b2942a952c12426370cf9b2c8588419250a2b5930b09ef19R70-R78) under a [pre-determined array of title option states](https://github.com/QutEcoacoustics/workbench-client/pull/2062/files#diff-a7029529e750e168b2942a952c12426370cf9b2c8588419250a2b5930b09ef19R25-R28)

This change was chosen as it allowed to test route titles under different conditions while not breaking or needing to refactor ever route fragments unit tests.

2023-06-07 23:44 UTC, merged