Add ng-http-caching request batching and caching
QutEcoacoustics/workbench-client pull request #2171
Opened 2024-11-18 05:42 UTC by hudson-newey

# Add ng-http-caching request batching and caching

## Changes

- Removes ng-cashew
- Adds ng-http-caching
- Migrates the admin panel caching debug tools to use ng-http-caching
- Adds unit tests to ensure the correct requests clear the http cache

## Issues

Fixes: #2159

## Visual Changes

None

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

2024-11-18 07:17 UTC, atruskie requested changes
Minor changes.

Most importantly, I can't see what the default TTL is. Remember this is a performance optimisation task, not a caching task. We don't need to reinvent the browser's cache, so we should be using a short TTL.

Measure the performance of this change:

- 2 pages
- 3 TTLs: 0, 200ms, 10 seconds, 60 seocnds
- 10 samples each

See if average load times change.

2024-11-18 07:17 UTC, atruskie commented on src/app/components/admin/settings/settings.component.spec.ts
> +});
there's no actual tests here

2024-11-18 07:17 UTC, atruskie commented on src/app/components/admin/settings/settings.component.ts
> +      Cache Time to Live (ms)
units

2024-11-18 07:17 UTC, atruskie commented on src/app/services/baw-api/baw-api.service.ts
> +    // keys that contain the item being deleted from cache
i don't understand what this means

2024-11-18 07:17 UTC, atruskie commented on src/app/services/baw-api/baw-api.service.ts
> +    // reference the item being deleted as an associated model.
i think you're overthinking this.

The method is documented as clearing the whole cache, and as long as usage is consistent with that, then we don't need all these extra notes.

The intent of this cache is reduce page load speeds for repeated items. It is intended to be very short lived - like 60 seconds. We shouldn't have to be invalidating it to often.

2024-11-18 07:17 UTC, atruskie commented on src/app/services/cache/cache-settings.ts
> +  public cacheTtlMs = NgHttpCachingConfigDefault.lifetime;
units

2024-11-18 07:17 UTC, atruskie commented on src/app/services/cache/ngHttpCachingConfig.ts
> +//
the current commented implementation of using object-hash is not ideal, and should be marked as such or removed

2024-11-18 23:30 UTC, hudson-newey commented on src/app/services/baw-api/baw-api.service.ts
> +    // keys that contain the item being deleted from cache
It was supposed to add a todo stating "instead of clearing the entire cache when a single item is updated, we should just delete that one item from the cache. However, when an model is updated/deleted, it may be used as an association to another model, meaning that we will have to invalidate the changed model, and any other models that reference the newly invalidated model".

However, since we have lowered the cache lifetime to one second and our caching is designed to reduce the impact of associations and N+1 queries, this is no longer a problem we have to worry about.

2024-11-18 23:58 UTC, hudson-newey commented on src/app/services/baw-api/baw-api.service.ts
> +    // reference the item being deleted as an associated model.
Discussed offline

I agree and have reduced the caching time

The purpose of this cache is not to re-create the browser cache but to consolidate duplicate association queries

2024-11-19 04:20 UTC, hudson-newey commented
## Performance test results:
### Performance test results

| Cache lifetime        | 1     | 2     | 3       | 4     | 5     | 6     | 7     | 8     | 9     | 10    |     | Average | Std-Deviation |
| --------------------- | ----- | ----- | ------- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | --- | ------- | ------------- |
| Baseline              | 0.852 | 3.285 | 3844.47 | 3.886 | 3.968 | 3.698 | 3.755 | 3.819 | 3.509 | 4.102 |     | 3.772   | 0.232         |
| 0ms (with debouncing) | 3.370 | 3.134 | 4048.85 | 3.225 | 3.664 | 3.935 | 3.370 | 2.731 | 3.496 | 3.410 |     | 3.438   | 0.383         |
| 200ms                 | 2.830 | 2.614 | 2801.27 | 3.436 | 3.676 | 3.232 | 3.086 | 3.200 | 3.339 | 3.274 |     | 3.149   | 0.322         |
| 10s                   | 3.179 | 3.047 | 3283.38 | 3.747 | 3.207 | 3.450 | 3.090 | 3.257 | 3.553 | 3.571 |     | 3.338   | 0.230         |
| 60s                   | 3.478 | 3.397 | 3341.24 | 3.152 | 3.191 | 2.997 | 3.182 | 2.681 | 3.426 | 3.331 |     | 3.218   | 0.239         |

2024-11-19 05:01 UTC, atruskie approved these changes

2024-11-19 05:09 UTC, atruskie commented
From discussion of the results we can see that the actual cache part of this library has little to no effect on performance. TTL does not seem to matter either. The main win is the request de-duplication.

so the understanding here is:
 
- debounce is effective at deduplicating requests for the same data on a page that is loading
- TTL has no effect unless more data is requested later by a user

We're going to trial 10 second TTL with the hope that for anyone doing any kind of quickly successive actions, they'll see a benefit from the cache (like flicking through pages of results). Also at the same time, anyone doing anything on a page is likely to take more than 10 seconds, stale cache results should basically be a non-issue.

We'll do some more testing when #2160 is implemented. #2170 should also help.

2024-11-20 00:22 UTC, merged