Authenticated Images
QutEcoacoustics/workbench-client pull request #300
Opened 2020-07-08 00:02 UTC by Allcharles

# Authenticated Images

Create authenticated image requests and handle defaults for model images.

## Changes

- Created `ImageDirective`
- Created `BawImage` decorator
- Update app `<img />` elements to use new directive

## Issues

- [ ] Need to append authentication token to urls
- [ ] Need to rename `ImageDirective` and `ImageDirectiveModule` to more descriptive names
- [ ] Tests are failing
- [ ] Need to write tests for decorator and directive
- [ ] Re-write card component tests to jasmine
- [ ] Create default image url if none provided for `BawImage` directive
- [ ] Edit `assertImage` function to assert that images are using the `ImageDirective`
- [ ] Rebase branch

## Closes

Closes #232 

## Final Checklist

- [ ] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing

2020-07-10 03:07 UTC, atruskie requested changes
Excellent work. I'd say the specs for the image directive need a little more descriptive documentation - as per the comment I think explaining what the test is testing in the test title would be enough.

Also ( i know we've talked about this before) but why not have the model decorator append the auth token?

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.spec.ts
> +    });
very minor nit: using more descriptive test names would act like documentation.

Instead of `should handle url error` maybe: `given an invalid url, it loads the next available url`

and:
 `given multiple bad urls, it tries to load each until one succeeds`

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.spec.ts
> +      assertImage(getImage(), imageUrls[2].url, "alt");
Don't hard code this index. Try `imageUrls.filter(x => x.size == imageSizes.MEDIUM).url`

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +  // tslint:disable-next-line: directive-selector
explain why we think it is ok to disable this warning

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +      this.imageRef.nativeElement.setAttribute("bawImage", "true");
Any other solution? This just seems like noise

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +    // On Component Initial Load
you should reset `srcIndex` if the input changes - it might be a new array, differently sized, or with different valid/invalid urls

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +  private srcIndex = 0;
another way you could handle tracking bad images would be to:
- tag the image object/url when it's faulty
- or keep a `Set<>` of URLs

Either way might make it easier to track bad urls. See comment about resetting index below

2020-07-10 03:07 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +  private retrieveThumbnailIfExists(): string | null {
could probably express this with a `.filter` for succinctness

2020-07-10 03:15 UTC, Allcharles commented
I had the AuthenticatedImageDirective handle appending authToken because it has better access to angulars DI. If I had it part of the decorator, it would require a minor rewrite of the generic decorator builder (not a huge problem), and the model does not always get instantiated with the injector service which I require to append the authToken (bit more of a problem, although I don't think this currently affects any cases in the app).

2020-07-13 02:16 UTC, atruskie approved these changes

2020-07-13 05:15 UTC, merged