Config refinement
QutEcoacoustics/workbench-client pull request #407
Opened 2020-08-21 01:19 UTC by Allcharles

# Configuration File Refinements

Refined how the configuration file works to match production expectations.

## Changes

- Removed the following properties from config:
  - `cmsRoot`
  - `assetRoot`
  - `siteDir`
  - `siteRoot`
- Added the following properties to config:
  - `environment.ga.domain`
- Fixed image directive bug where fallback image failing would cause an infinite loop
- Enhanced error message when cms values are improperly set

## Issues

Closes #403
Closes #402 
Closes #401 

## Visual Changes

Example of CMS page failing to load
![image](https://user-images.githubusercontent.com/3955116/90841480-226c0b00-e3a0-11ea-9e8b-20a3da996ea2.png)

2020-08-21 02:46 UTC, Allcharles commented
Noticed a mistake, image.directive should not prepend /assets to local resources

2020-08-22 01:29 UTC, atruskie requested changes
So the urls for the expectOne in the tests for CMS will change once feature is implemented. Fine for now though.

I'd like to see the removal of asset URL modifying code in the image directive. Assets should be known values for us, in which case we should be able to construct the URLS in a principled fashion.

2020-08-22 01:29 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +      return "/assets" + url;
this should be an app-wide constant

2020-08-22 01:29 UTC, atruskie commented on src/app/directives/image/image.directive.ts
> +      return "/assets" + url;
Actually, I have an issue with this entire function. We shouldn't be formatting a URL. URLs passed to image direction should be valid or not valid.

2020-08-22 01:29 UTC, atruskie commented on src/app/services/app-config/app-config.service.ts
> +      : "/assets/content/error.html";
I won't mandate this for this PR, but this will end up as a HTTP REST service, just like any other API call

2020-08-23 22:37 UTC, Allcharles commented
Had a private discussion, and the following behaviour should be achieved by this PR:

Remove the following from `environment.json`:

- assetRoot
- cmsRoot

Handle urls the following ways
- local resources (workbench-client):
  - Relative urls: siteDir (config) + assetDir (defined in app) + name
  - Absolute urls: siteRoot (config) + assetDir (defined in app) + name
- api resources:
  - Relative urls: apiRoot + name
  - Absolute urls: name

2020-08-27 00:43 UTC, Allcharles commented
I'm going to separate this work into two different PRs: Fixing SecureImageDirective bug, and applying config changes. This PR wont be fixed, however its being left so I can extract code, and read reviews

2020-08-27 03:56 UTC, closed without merging

2020-08-27 06:20 UTC, Allcharles commented
Closed in favour of #423 and #422