Eslint migration
QutEcoacoustics/workbench-client pull request #607
Opened 2020-11-22 08:55 UTC by Allcharles

# Upgraded from TSLint to ESLint

Upgraded from TSLint which has been deprecated for the past year.

## Final Checklist

- [x] Assign reviewers if you have permission
- [x] Assign labels if you have permission
- [x] Link issues related to PR
- [x] Ensure project linter is not producing any warnings (`npm run lint`)
- [x] Ensure build is passing on all browsers (`npm run test:all`)
- [x] Ensure CI build is passing

2020-11-22 11:17 UTC, Allcharles commented
Still need to address some issues with ESLint hitting and OOM problem. Will solve by extending the RAM limit of node

2020-11-23 03:21 UTC, atruskie requested changes
all those naming convention disables add noise.

might as well make this a cleanup PR and get them all done

2020-11-23 03:21 UTC, atruskie commented on .eslintrc.json
> +        // TODO Re-enable
link to issue?

2020-11-23 04:51 UTC, atruskie commented
Squash this before merging

2020-11-25 02:55 UTC, atruskie approved these changes

2020-11-25 03:11 UTC, merged