Seconday Menu Indentation System
QutEcoacoustics/workbench-client pull request #81
Opened 2020-01-23 23:28 UTC by Allcharles

Improved secondary menu indentation system so that indentation does not need to be defined by page components. Components specify their parent, which is then used to calculate its indentation level and organise sub-links.

Closes #58

2020-01-24 00:08 UTC, atruskie requested changes
Okay. So the original reason that I very intentionally set the indentation to a user-controlled integer is that it is simple. The menu indentation is something that very rarely changes, and as an integer is super easy to fix. More than all of that, it is fast!

Making the indentation value dynamic means there are fewer chances for the value to be incorrect, so I'm willing to entertain this idea.

However, the current implementation has worse theoretical performance; it went from O(1) to O(2N).

So here's the solution I'd like you to try and get to:

When a menu item is created, it directly keeps a reference to its parent. When that happens it gets the parent's indentation level, adds one and stores the indentation value on itself. 
In this way, lookup of indentation values is O(1) (which is good because lookup happens many times).
The flaw here is if we need to change indentation value while the app is running - but that is not a requirement we have yet, and if we do need to we can recompute the chain once, rather than on every render.

2020-01-24 00:08 UTC, atruskie commented on src/app/interfaces/menusInterfaces.ts
> +  indentation?: number;
if this option is no longer user-configurable  then let's remove it from the interface

2020-01-24 00:08 UTC, atruskie commented on src/app/component/shared/secondary-menu/secondary-menu.component.ts
> +          indentation++;
Hmmmm... recursive loop

2020-01-24 00:08 UTC, atruskie commented on src/app/component/shared/secondary-menu/secondary-menu.component.ts
> +        parentMenuRoutes.forEach(parent => {
it isn't readily obvious why you have to set indentation on parent routes?

This loop has the potential to run many times...

2020-01-24 07:04 UTC, Allcharles commented on src/app/interfaces/menusInterfaces.ts
> +  indentation?: number;
I am unsure how to remove this, there is no way i can pass the indentation value of the menu item outside of the values specified in the interface. The only option i have is to turn all of the menu item types into classes which would be a bit of a rewrite.

2020-01-24 07:10 UTC, Allcharles commented
I have updated the system to try follow your ideas. Currently the major change i have made is that i have hijacked the functions you created to automatically set the kind value of the interfaces. Those functions now calculate the order and indentation of the item depending on a couple conditions. Ive highlighted the important bits below:

```javascript
export function MenuLink<T extends Omit<MenuLink, "kind">>(item: T): MenuLink {
  return Object.assign(item, {
    kind: "MenuLink" as "MenuLink",
    indentation: 0
  });
}
export function MenuRoute<T extends Omit<MenuRoute, "kind">>(
  item: T
): MenuRoute {
  return Object.assign(item, {
    kind: "MenuRoute" as "MenuRoute",
    indentation: item.parent ? item.parent.indentation + 1 : 0,
    order: item.parent ? item.parent.order : item.order
  });
}
export function MenuAction<T extends Omit<MenuAction, "kind">>(
  item: T
): MenuAction {
  return Object.assign(item, {
    kind: "MenuAction" as "MenuAction",
    indentation: 0
  });
}
```

The only concern i have about this method is that it relies on the programmer using the correct value when creating menus. There is no check currently which throws an error if a menu item is not using the function instead of the interface. A potential solution is to check if the `kind`, `order`, and `indentation` keys have been set inside the menu component. Anything without all three defined must be a mistake where someone has instantiated an interface instead of calling the function.

2020-01-29 11:41 UTC, atruskie approved these changes

2020-01-29 11:41 UTC, merged