Model viewUrl query parameters
QutEcoacoustics/workbench-client pull request #877
Opened 2021-02-16 05:22 UTC by Allcharles

# Update viewUrl to handle query paramaters

Updated how the `viewUrl` for models works, and how they interact with the angular router.

## Changes

- Created `UriDirective`
- Updated models to return viewUrls including query parameters

## Issues

Closes #772 

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

2021-02-16 07:01 UTC, atruskie requested changes
Fantastic work. 

Minor changes:
-  `uri` should be `url`
- We should add a section to contributing.md that explains what custom directives are in use (particularly since these could appear magical or external/angular supplied directives)
- You used the `string` and `format` pairing a lot. Is there a reason for that over `UrlTree` and `formatUrlTree`? Technically it's more work for the browser - though it is unlikely to be a significant performance penalty
- I think you need a consistent approach for dealing with urls that are not yet ready. In this review I saw:
    - throwing an exception
    - returning `""`
    - returning `"not_implemented"`
    - returning `""/play_url"`
    - various combinations of the above with and without console errors or warns

2021-02-16 07:01 UTC, atruskie commented on src/app/test/helpers/html.ts
> +  expect(target).toHaveAttribute("href", encodeURI(route));
rename uri to url

2021-02-16 07:01 UTC, atruskie commented on src/app/models/Tag.ts
> +    return libraryMenuItem.route.format(undefined, {
this `undefined` seems strange - is there a reason for it?

I'm going to guess we're omitting a route parameter? But which one?

2021-02-16 07:01 UTC, atruskie commented on src/app/models/Script.ts
> +    return "not_implemented";
throw - this will just lead to a _misleading_ 404

Is there a reason we can't just return the properly formed url? It will still 404 but at least it is self fixing when the associated view is eventually created

2021-02-16 07:01 UTC, atruskie commented on src/app/models/SavedSearch.ts
>      return "not_implemented";
See comments on script.ts - should not return "not_implemented"

2021-02-16 07:01 UTC, atruskie commented on src/app/models/AbstractModel.ts
> +   * TODO Update comment
carpe diem

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/uri/uri.directive.ts
> +  selector: "a[uri]",
`uri` ➡`url`

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/uri/uri.directive.ts
> +  selector: "a[uri]",
I know we talked about documenting over namespacing, but https://angular.io/guide/styleguide#directive-custom-prefix is a compelling argument. 

Suggested `bawUrl`

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/uri/uri.directive.ts
> +  @Input() public uri: string;
Does not match specification from #772: `string | UrlTree`

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/uri/uri.directive.ts
> +    return this._router.createUrlTree([url.pathname], {
Why not: [`parseUrl`](https://angular.io/api/router/Router#parseurl) as defined in spec?

It handles the all the cases you handle manually: https://github.com/angular/angular/blob/e3f09ce845cef9fd2c89d39d0d822114c51e68fa/packages/router/src/url_tree.ts#L289-L294

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/uri/uri.directive.ts
> +    return this._router.createUrlTree([url.pathname], {
You can use object.assign to then merge in the base directive params with the created urlTree

2021-02-16 07:01 UTC, atruskie commented on src/app/directives/strongRoute/strong-route.directive.ts
> +}
repeated function in uri.directive.ts

2021-02-18 11:34 UTC, Allcharles commented on src/app/models/Tag.ts
> +    return libraryMenuItem.route.format(undefined, {
`libraryMenuItem` has no route parameters

2021-02-18 23:31 UTC, Allcharles commented
Alright, I see a few comments related to `UrlTree` and `parseUrl` so I'll answer them here. I can only create `UrlTree`s if I have access to the `Router` and `ActivatedRoute` injectables unfortunately. As the models are currently implemented, they do not have guaranteed access to the angular DI. So I cannot use it as a viable system. As for `parseUrl`, as I suspected during our talks, it sanitizes query parameters which defeats the purpose of using it. the `URL` class handles all of the logic we need with minimal hacking.

2021-03-10 03:22 UTC, atruskie approved these changes
Perfect

2021-03-10 10:50 UTC, merged