Extract Environment
QutEcoacoustics/workbench-client pull request #96
Opened 2020-02-13 01:27 UTC by Allcharles

Extracted the environment variables from the application for the inevitable push to deployment.

This should allow a build environment to easily select an environment to push with the build to switch it between development, staging, and production. Currently this environment file only stores the external configs location on the BAW Server (currently redirects to workbench-client as route does not exist).

With this update there are three types of environments:

- Build environment
  - This is baked into the application and cannot be changed after build
- Deployment environment
  - This is the environment which can be changed after build time. This stores information about whether the system is accessing the staging or production server
- Config
  - This is the downloaded config file from the BAW Server. It stores all values that should change between staging and production versions of the application.

Closes #90 
Closes #91

2020-02-13 12:01 UTC, atruskie requested changes
Okay.

Delete the following files:

- src/assets/config/development.json
- src/assets/config/production.json
- src/assets/config/staging.json
- src/assets/config/
- src/assets/environment/environment.json
- src/assets/environment/environment.production.json
- src/assets/environment/environment.staging.json

Now add: 

- src/assets/environment.json

The contents of which will have the structure of the  `Configuration` interface.

Then, simplify the rest of this code.

2020-02-13 12:01 UTC, atruskie commented on src/app/app.helper.ts
> +import { MockAppConfigService } from "./services/app-config/appConfigMock.service";
I guess I'll find out what `MockAppConfig` is below... but the name is suspicious. Mocks should only be used in tests...

2020-02-13 12:01 UTC, atruskie commented on src/app/services/app-config/app-config.service.ts
> +        );
I'm not sure in which case this condition would occur. Even if it does, why is it an error?

2020-02-13 12:01 UTC, atruskie commented on src/app/services/app-config/app-config.service.ts
> +    .then((configUrl: string) => fetch(configUrl))
Ok officially confused. Why are we fetching two things from the server?

2020-02-13 12:01 UTC, atruskie commented on src/app/app.helper.ts
> +import { MockAppConfigService } from "./services/app-config/appConfigMock.service";
Yeah, it is a test feature. Code in test files, even if just a named constant, should never bleed back into source code.

Try inverting it:
- Define an APP_CONFIG symbol in app-config and override the injection of that symbol in the tests only.

2020-02-14 01:52 UTC, Allcharles commented on src/app/app.helper.ts
> +import { MockAppConfigService } from "./services/app-config/appConfigMock.service";
`APP_CONFIG` is no longer used

2020-02-14 01:55 UTC, atruskie approved these changes

2020-02-14 02:58 UTC, merged