Data request Page
QutEcoacoustics/workbench-client pull request #968
Opened 2021-04-12 06:06 UTC by Allcharles

# Implemented Data Request Page

## Changes

- Created `simpleFormTemplate` class for forms which do not navigate after submission
  - Potentially should rename to make `simpleFormTemplate` and `formTemplate` to simpler to understand the difference
- Updated @voo/tzdb library for https://github.com/vvo/tzdb/pull/163
- Implemented Data Request page and forms

## Problems

- Did not add tests because either, its too tricky to implement (ie. Blob downloading), or page has temporary implementation

## Issues

Deals with #614
Deals with #610

## Final Checklist

- [ ] Assign reviewers if you have permission
- [ ] Assign labels if you have permission
- [ ] Link issues related to PR
- [ ] Ensure project linter is not producing any warnings (`npm run lint`)
- [ ] Ensure build is passing on all browsers (`npm run test:all`)
- [ ] Ensure CI build is passing
- [ ] Ensure docker container is passing ([docs](https://github.com/QutEcoacoustics/workbench-client#docker))

2021-04-13 02:30 UTC, atruskie requested changes
I'm not convinced you need the separate form component. If you don't want the form to navigate, why not just don't navigate by default?

I'm quite confused with how the annotation download component works. It looks like it takes a combination of `@input` bindings and QSPs? AFAIK it should only take QSP...

I think this stems from jamming two forms into one page. Split the pages and this should be cleaned up.

Default timezone for download annotations is the local time zone of the `site`, or fallback to local timezone of the browser.

The download annotations page should just generate a href button link. Doesn't need to be a form, doesn't need an API service (currently)

2021-04-13 02:30 UTC, atruskie commented on src/app/app.helper.ts
> +}
Why is this needed?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +import { Component, Input, OnInit } from "@angular/core";
I would name this `annotations-download` - the name `annotations` is likely a name we'll want to use elsewhere for other annotation related things

**EDIT**: I see you've given the component a more precise name, change name of file to match?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +  selector: "baw-request-annotations",
`baw-download-annotations`

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +        Please select the timezone for the CSV file containing annotations for
Let's take the chance to improve this copy:

> The annotations in the CSV will have all their dates and times set to a time zone of your choice.
> The default time zone is the local time for the site where the audio was recorded.
>
> For example, annotations created for audio from Brisbane will have dates and times set to AEST (+10).
>
> However, if you have recordings from Brisbane and Perth, which time zone do we choose for all downloaded events?
> AEST (+10) or AWST (+8) or UTC (+0)?
>
> It depends on how you want to work with your data, so the choice is yours.
> Please select the time zone you wish to use:

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +        "Successfully downloaded annotations. Please accept pop-ups if they are disabled.",
Pop-ups should not be required

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +    }
This seems like a specific case - what is going on here?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +    const { timezoneName, projectId } = this.route.snapshot.queryParams;
maybe be region or site id specified as well

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +    }
This information should be pulled from the project/site/region id's

For projects: select the most frequent timezone from the sites within it

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +    }
why is a username needed?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +      this.modelName = (this.region ?? this.site).name;
what is `modelName` for?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +  private project: Project;
Document these

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/annotations/annotations.component.ts
> +}
should just be forming a URL

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/data-request.component.ts
> +    </ng-container>
let's split this into two separate pages - there's no need for them to be on the same page

2021-04-13 02:30 UTC, atruskie commented on src/app/components/data-request/data-request.menus.ts
> +    timezoneName: params?.timezoneName ?? params?.selected_timezone_name,
I appreciate that you added support for this, but this link will never be generated by the old-client, and the server will never need to redirect a user to this page with the old style QSPs, so redundant?

2021-04-13 02:30 UTC, atruskie commented on src/app/components/shared/formly/custom-inputs.module.ts
> +      defaultValue: Intl.DateTimeFormat().resolvedOptions().timeZone,
Not the server? This is client code?

2021-04-13 02:30 UTC, atruskie commented on src/app/helpers/advancedTypes.ts
> +export interface FixedLengthTuple<T extends any, L extends number>
A tuple by definition is fixed length

2021-04-13 02:30 UTC, atruskie commented on src/app/services/baw-api/account/accounts.service.ts
> +    );
why is a user id needed

2021-04-13 02:30 UTC, atruskie commented on src/app/services/baw-api/baw-api.service.ts
> +
...should not be needed with other suggested changes

2021-04-13 02:30 UTC, atruskie commented on src/app/services/baw-api/region/regions.service.ts
> +  }
this should just be a route to the download annotations page

2021-04-13 02:30 UTC, atruskie commented on src/app/services/baw-api/site/sites.service.ts
> +  }
a above, should not be a service call

2021-05-10 23:17 UTC, Allcharles commented
Closed in favour of #1044

2021-05-10 23:17 UTC, closed without merging